Repository confluentinc/librdkafka, pull requests merged in 2018-10, with the labels that each got.

#2038 Fix LTO warning with gcc 8.
  src/rdaddr.c
Labels: portability

#2028 Fixing Counting error in rdkafka_performance #1542
  examples/rdkafka_performance.c
Labels: bug

#2054 KIP-62: add support for max processing time (max.poll.interval.ms)
  CONFIGURATION.md
  INTRODUCTION.md
  STATISTICS.md
  src-cpp/rdkafkacpp.h
  src/rdkafka.c
  src/rdkafka.h
  src/rdkafka_cgrp.c
  src/rdkafka_cgrp.h
  src/rdkafka_conf.c
  src/rdkafka_conf.h
  src/rdkafka_int.h
  src/rdkafka_request.c
  tests/0089-max_poll_interval.c
  tests/CMakeLists.txt
  tests/test.c
  win32/tests/tests.vcxproj
Labels: enhancement
